### ISSUE TITLE
Uzivatelia MD

### ISSUE THREAD

**Issue by eurosecom** [eurosecom/eurosecom#184]

**Comment by eurosecom** [comment]
- buttony pageprev a pagenext sa chovajú ako submity pre form3, prerob
buď na iný typ alebo ukonči form3 pred buttonami inak sa buttony nedajú použiť ako odkaz na predch.strana alebo ďalšia alebo úprava položky....

**Comment by eurosecom** [comment]
Ten návrhový vzor z linku https://getmdl.io/components/index.html#layout-section keď tam vložím bez zmien tak nie je funkčný. Vôbec mi nezobrazí ani menu ani základný content.
Ak chceš použiť nejaký návrhový vzor, v prvom kroku ho musíš rozchodiť bez zmien a až potom postupne robiť úpravy.
Inak je problém  upravovať návrhové vzory.
Skús vložiť bez zmien medzi td a fprm ----- /form /td tak aby chodil.

**Comment by eurosecom** [comment]
IE 11 v úprave užívateľa nevidím prepínač aktívny ani tlačítko uložiť.
V skriptoch, firmách a grid ok.
Ak dám menšiu lupu urobí váčšiu medzeru z ľava a pravú stranu nevidím ani tak.
![uziv](https://cloud.githubusercontent.com/assets/8501403/26792929/5c4a61c6-4a1c-11e7-87ee-d5b5d2bac92d.png)
![uzivlupa75](https://cloud.githubusercontent.com/assets/8501403/26793002/9fff64ca-4a1c-11e7-8ca8-fd5a3dd518e9.png)

**Comment by 61Stan** [comment]
Preboha to čo máte za prehliadač. Skúste v chrome. Ja to až na konci testujem v iných prehliadačoch. Nechcem si robiť nervy viackrát.

**Comment by eurosecom** [comment]
To vyzerá na nejaký bug, treba to pozrieť aby to neviedlo k nejakej zmene koncepcie kvôli nekompatibilite IE a chrome

**Comment by eurosecom** [comment]
POZOR !!!! Zásadný problém, v novej koncepcii nám po stlačení Enter preblikne a ukladá celý formulár. V tej predchádzajúcej to nerobil.

**Comment by 61Stan** [comment]
Samozrejme že enter preblikne, keď to nie je ošetrené. Nie je tam žiadne uvolni a iné "špeciality". Ja to stále nechápem= ideme sa veľmi hrať, že material dizajn a pritom na každom kroku to prasíme. V pôvodnom nastavení firiem a skriptov nebol ošetrné uvolni enter.
Ukážka funkčného vyhľadávania (vpravo hore lupa) https://material.io/guidelines/components/data-tables.html#data-tables-tables-within-cards  (lupa zároveň rozbaľuje aj vyhľadáva, príp. sa dá použiť enter)
Samozrejme, že to takto nestrávime, takže to zase nejak obídem a dám tam natvrdo input. Zabudol som, my musíme preblikávať.

Teraz k veci:
- tlačidlo "uložiť" musí byť v sekcii "grid karta"?
- mám nachystať obalovač pre uložiť a bude uvolni?
- zákaz mazania užívateľa platí? Ak áno, tak vymažem všetko s tým súvisiace.
- Nápad: číselník skriptov riešiť cez .txt súbor a mysql, kde budem môcť zapisovať číslo skriptu,názov skriptu,podsystém a tento súbor mi naplní nápovedu v úprave užívateľa v sekcii grid. Jednoducho, nechcem natvrdo upravovať nápovedu v úprave užívateľa, ale len interný číselník. Rovnaký princíp, by sa dal použiť napr. na číselník bánk s numb a bic. Bude technicky a logicky možné?

**Comment by eurosecom** [comment]
- tlačidlo "uložiť" nemusí byť v sekcii "grid karta"?
- nachystať obalovač pre uložiť a bude uvolni?
- zákaz mazania užívateľa platí
- nápad dobrý ale teraz by som to neriešil, rád by som sa už posunul k skriptom pre užívateľov

**Comment by 61Stan** [comment]
Skúšal som na ie10. U mňa layout vyzerá OK. Prosím rozbehajte prihlasovanie "/f" na eshoptest, aby som mohol skúšať vo viacerých verziách ie. K edge sa nedostanem. Otázne na ktorý prehliadač sa zameriame, v ktorom to bude ok, ostatné plus mínus.
![ie10_uprava](https://user-images.githubusercontent.com/8523540/27067547-b2a02d54-500b-11e7-94b5-8f5feb85644c.png)
![ie10_zoznam](https://user-images.githubusercontent.com/8523540/27067546-b29848be-500b-11e7-8142-75bfc440303e.png)

**Comment by eurosecom** [comment]
Pošli posledné úpravy na GitHub, to čo tam je mi nechodí v IE11.

**Comment by 61Stan** [comment]
Nič som nerobil, potrebujem eshoptest.sk, aby som vedel testovať ie10 a ie11.

**Comment by eurosecom** [comment]
Skús poslať znovu poslednú lebo v obrázkoch je nejaká nová s horizontálnym prepínačom sekcií a ja mám ešte tú vertikálnu čo nechodila v IE, synchro mi nesťahuje novú

**Comment by 61Stan** [comment]
Horizontálny prepínač = bug na ie10. Ešte som to neošetroval. Opakujem = nič som nerobil, pretože to potrebujem vidieť na jednom počítači na ie10 i 11, aby som vedel od čoho sa odraziť.

**Comment by eurosecom** [comment]
Re: Keď dám nový užívateľ, tak mi urobí užívateľa (číslo id), ktorého už mám v zozname s najnižším číslom.	
Aby neuložil to isté ID je zabezpečené na úrovni MySql. Skontroluj či máš v talulke klienti pri položke id_klienta nastavené autoincrement a primary key

**Comment by 61Stan** [comment]
Toto mám na locale
![local_klienti](https://user-images.githubusercontent.com/8523540/29022089-2ccb2278-7b68-11e7-9205-610c96fc5350.png)

**Comment by 61Stan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Faktúry zoznam [184]](https://trello.com/c/oBDr0rP5/7-fakt%C3%BAry-zoznam-184)

**Comment by 61Stan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Uzivatelia [184]](https://trello.com/c/oBDr0rP5/7-uzivatelia-184)
