### ISSUE TITLE
Firmy MD

### ISSUE THREAD

**Issue by 61Stan** [eurosecom/eurosecom#185]

**Comment by 61Stan** [comment]
Stále platí, že prihlasovacia stránka musí byť vo zvlášť okne/záložke?

**Comment by eurosecom** [comment]
Ano kvoli bezpecnosti

**Comment by eurosecom** [comment]
- v tabuľke najprv riadky s echo potom form, znamená, že keď klikneš Novú položku tak FORM pre novú položku zobrazí až za prvou položkou...., preto sme to prehadzovali aby form pre novú položku bol prvý v zozname ak už chceme zoznam aj pri novej položke, čo by som osobne možno ani nezobrazoval zoznam pri novej položke ale len form pre novú položku a žiadny zoznam, ktorý sa mi zdá zbytočný v tom prípade

**Comment by 61Stan** [comment]
Vrátim späť. Pri vypĺňaní novej položky potrebujem údaje v iných položkách. Napr. enpo pri nastavení obyčajného užívateľa.

**Comment by 61Stan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Firmy [185]](https://trello.com/c/Gtzzlugi/11-firmy-185)
