### ISSUE TITLE
Ucto MD

### ISSUE THREAD

**Issue by 61Stan** [eurosecom/eurosecom#187]
Hlavné menu účtovníctva

**Comment by eurosecom** [comment]
- Filozofia a face super, o odkazoch okamžite klikateľných sa zatiaľ asi nebavíme, určite tam ale chýbajú dva najpoužívanejšie body po nahrávaní, pohyby na účte a vyhľadávanie v dokladoch
- časový harmonogram, kedy podať priznanie a štatistiku, kedy zaplatiť mzdy a dph... aj s notifikáciou na mobil - nedorobené
- názov firmy v ufir je z www.orsr.sk, tam musí byť názov z fir tak ako je

**Comment by 61Stan** [comment]
Mám predstavu do konca týždňa:
- odkazy dám klikateľné, tam stačí len vyplniť onclick="" a zabezpečiť, aby sa užívateľ dostal ku všetkým bodom. Čiže všetky súbory z hlavného menu, už budú mať "_md" len budú v starom dizajne a postupne budem prerábať. Aby bolo reálne použiteľné v praxi. 
- pohyby na účte a vyhľadávanie chcem cez jeden bod = lupa v záhlaví. V podstate v záhlaví budú nástroje = vyhľadávanie, záloha, prenos, ostré spracovanie, kontrola. Možno by bolo dobré v každom skripte volanom z hlavného menu odkaz na vyhľadávanie (bude stále po ruke), potom by som presunul do najvyššieho riadku.
- neviem či nastavenia mám dať cez .card, alebo zatiaľ nechať tak. Je ich veľa. Napadlo ma, že druhy dokladov roztriediť do jednotlivých dokladov vo vstupe dát a do nastavení dať odkaz druhy dokladov.
- časový harmonogram / kalendár = super myšlienka. Teraz sa zameráme na holý základ programu = hlavné menu a odkazy z hlavného menu.
- ufir som chcel, aby ste mi rozbehali premennú (názov firmy z ufir) aby som mohol dať do karty číselníky

**Comment by 61Stan** [comment]
Zatiaľ nič nerobiť so súborom. Chytil vírus.

**Comment by eurosecom** [comment]
- malo by sa dať focusovanému riadku rádia zmeniť class na nejakú inú farbu, tá malá bodka checku nie je moc výrazná

**Comment by 61Stan** [comment]
Spravím takto:
https://www.youtube.com/watch?v=2UMpdFtx3Ew

**Comment by 61Stan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Účtovníctvo hlavné menu](https://trello.com/c/4GRGHuYj/12-%C3%BA%C4%8Dtovn%C3%ADctvo-hlavn%C3%A9-menu)
